export const{
  FETCH_AUTHOR = 'FETCH_AUTHOR',
  CREATED_AUTHOR = 'CREATED_AUTHOR',
  UPDATED_AUTHOR = 'UPDATED_AUTHOR',
  DELETED_AUTHOR = 'DELETED_AUTHOR'
}
export default{
  FETCH_AUTHOR,
  CREATED_AUTHOR,
  UPDATED_AUTHOR,
  DELETED_AUTHOR
}
