export const FETCH_AUTHOR = 'FETCH_AUTHOR'
export const CREATED_AUTHOR = 'CREATED_AUTHOR'
export const UPDATED_AUTHOR = 'UPDATED_AUTHOR'
export const DELETED_AUTHOR = 'DELETED_AUTHOR'

export default{
  FETCH_AUTHOR,
  CREATED_AUTHOR,
  UPDATED_AUTHOR,
  DELETED_AUTHOR
}
