# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91e2be8e8a2c1da1f4bd912ff5ecdc8fe9e7cee22256a769d9416a5bb24b934af08db9a850ba43480265b7ddfdc7078a4ca3a799afc01caf1d879ea8376c63e9

test:
  secret_key_base: 4d352aaf57c610d28b24dde9485e66f4db3efd8fcc1a234d5a21e556716b097bc268f4b05c8e7d6e26855c1077889b9f38c672480a3bd599b4e4d6092bae8629

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
